var r = require('ngv-jest-platform');
var _0 = require("..\\..\\..\\..\\..\\..\\sabre-ngv-app\\module.js");
var _1 = require("..\\..\\..\\..\\..\\..\\sabre-ngv-core\\module.js");
var _2 = require("..\\..\\..\\..\\..\\..\\sabre-ngv-xp\\module.js");
var _3 = require("..\\..\\..\\..\\..\\..\\sabre-ngv-hints\\module.js");
var _4 = require("..\\..\\..\\..\\..\\..\\sabre-ngv-redAppSidePanel\\module.js");
var _5 = require("..\\..\\..\\..\\..\\..\\sabre-ngv-sidepanel\\module.js");
var _6 = require("..\\..\\..\\..\\..\\..\\sabre-ngv-UIComponents-utils\\module.js");
var _7 = require("..\\..\\..\\..\\..\\..\\sabre-ngv-UIComponents\\module.js");
var _8 = require("..\\..\\..\\..\\..\\module.js");

var module=r.require("com-sabre-tn-redapp-example-workflow-mod/views/lfsResults/LfsTilePopOver");
r.initModule({"name":"com-sabre-tn-redapp-example-workflow-mod","version":"5.0.0","meta":{},"dependencies":["sabre-ngv-app","sabre-ngv-core","sabre-ngv-xp","sabre-ngv-hints","sabre-ngv-redAppSidePanel"],"workflows":[],"extensions":[],"submodules":["com-sabre-tn-redapp-example-workflow-mod/common/Consts","com-sabre-tn-redapp-example-workflow-mod/common/CustomXTPointService","com-sabre-tn-redapp-example-workflow-mod/common/ICustomXTPointService","com-sabre-tn-redapp-example-workflow-mod/common/WorkFlowListener","com-sabre-tn-redapp-example-workflow-mod/Context","com-sabre-tn-redapp-example-workflow-mod/index","com-sabre-tn-redapp-example-workflow-mod/Main","com-sabre-tn-redapp-example-workflow-mod/models/CustomSvcRQ","com-sabre-tn-redapp-example-workflow-mod/models/CustomSvcRQData","com-sabre-tn-redapp-example-workflow-mod/models/CustomSvcRS","com-sabre-tn-redapp-example-workflow-mod/models/ICustomSvcRQ","com-sabre-tn-redapp-example-workflow-mod/models/ManualExtensionPointEventData","com-sabre-tn-redapp-example-workflow-mod/models/SampleResult","com-sabre-tn-redapp-example-workflow-mod/models/SampleResults","com-sabre-tn-redapp-example-workflow-mod/models/SearchFormRequest","com-sabre-tn-redapp-example-workflow-mod/models/SearchFormRequestData","com-sabre-tn-redapp-example-workflow-mod/views/cmdHelperForm/Action","com-sabre-tn-redapp-example-workflow-mod/views/cmdHelperForm/CmdHelperButton","com-sabre-tn-redapp-example-workflow-mod/views/cmdHelperForm/reducers","com-sabre-tn-redapp-example-workflow-mod/views/cmdHelperForm/sagas","com-sabre-tn-redapp-example-workflow-mod/views/cmdHelperForm/State","com-sabre-tn-redapp-example-workflow-mod/views/cmdHelperForm/types","com-sabre-tn-redapp-example-workflow-mod/views/customFlows/HelperFlowsView","com-sabre-tn-redapp-example-workflow-mod/views/customFlows/MessageView","com-sabre-tn-redapp-example-workflow-mod/views/customFlows/QCCheckView","com-sabre-tn-redapp-example-workflow-mod/views/customFlows/ShellPnrView","com-sabre-tn-redapp-example-workflow-mod/views/decisionSupport/DsDrawerTile","com-sabre-tn-redapp-example-workflow-mod/views/decisionSupport/DsTilePopOver","com-sabre-tn-redapp-example-workflow-mod/views/lfsResults/LfsDrawerTile","com-sabre-tn-redapp-example-workflow-mod/views/lfsResults/LfsTilePopOver","com-sabre-tn-redapp-example-workflow-mod/views/modalDialog/ExtPointManualView","com-sabre-tn-redapp-example-workflow-mod/views/renderRS/DrawerDescriptorOptions","com-sabre-tn-redapp-example-workflow-mod/views/renderRS/RSActionPopup","com-sabre-tn-redapp-example-workflow-mod/views/renderRS/RSResultArea","com-sabre-tn-redapp-example-workflow-mod/views/renderRS/RSResultPanel","com-sabre-tn-redapp-example-workflow-mod/views/renderRS/RSResultRow","com-sabre-tn-redapp-example-workflow-mod/common/CQHint","com-sabre-tn-redapp-example-workflow-mod/views/cmdHelperForm/Form"],"hasTemplates":true,"hasStyles":true});
for(var i in module){if(module.hasOwnProperty(i)){exports[i] = module[i]}}
